In [1]:
import numpy as np

In [2]:
myArray=np.array([[1,2,3,4,5]],np.int8)

In [3]:
myArray


array([[1, 2, 3, 4, 5]], dtype=int8)

In [4]:
myArray.shape

(1, 5)

In [5]:
myArray[0,1]

np.int8(2)

In [6]:
lnspace=np.linspace(1,5,4)

In [7]:
lnspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [8]:
arr=np.empty(5)

In [9]:
arr

array([0.00000000e+000, 1.05433704e-311, 1.05433705e-311, 1.05433704e-311,
       3.14083114e-317])

In [10]:
arr1=np.empty((4,6))

In [11]:
arr1


array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.78019082e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.24610383e-306,
        6.89804132e-307, 1.69121096e-306, 8.34449382e-308]])

In [13]:
arr2=np.empty_like(lnspace)

In [14]:
arr2

array([1.05433704e-311, 1.05433705e-311, 1.05433704e-311, 3.14083114e-317])

In [15]:
arr=np.arange(45)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [17]:
arr.reshape(3,15)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [18]:
arr.reshape(45)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [19]:
 arr=arr.reshape(3,15)

In [20]:
arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [22]:
arr=arr.reshape(45)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [24]:
arr=arr.reshape(3,15)


In [25]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [29]:
arr=arr.ravel()

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [31]:
 arr.shape


(45,)

In [36]:
 arr99=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [40]:
ar=np.array(x)

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
ar.sum(axis = 0)

array([12, 15, 18])

In [44]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [46]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [47]:
 ar.flat


In [50]:
for item in ar.flat:
    print (item)

1
2
3
4
5
6
7
8
9


In [51]:
arr2.size


4

In [52]:
ar.size


9

In [53]:
ar.ndim

2

In [54]:
ar.nbytes


72

In [55]:
ar.argmax()

np.int64(8)

In [56]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])